services:
  postgres:
    ports:
      - "5432:5432"

  clickhouse:
    ports:
      - "8123:8123"
      - "9000:9000"

  redis:
    ports:
      - "6379:6379"

  gateway:
    ports:
      - "8080:8080"
