ALTER TABLE devices ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]';
ALTER TABLE alerts ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]';
ALTER TABLE maintenance_windows ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]';
